### PR TITLE
added BCH-DNS

### PR DESCRIPTION
**Pull request by kosinusbch**

### CODE REVIEW

**Comment by jcramer** [comment]
Hi Kosinus, I am not the maintainer of this repo but I had a thought about your BCH-DNS project.  

I am working on a project called Simple Ledger Protocol that maybe you and I could collaborate on since it may be very similar to yours.  It may be a way for us to join forces and accelerate each of our project's progress...  Would you please read the second bullet point I've just add to my repo and let me know what you think? [Draft Specifications](https://github.com/simpleledger/simple-ledger-protocol/blob/master/README.md)

If you want to continue on our own separate paths, I understand, but just thought I'd offer as I think there is some overlap between projects.

Also the first byte in your hex id should be less than `10` where you have `80`.

**Comment by vermorel** [comment]
Hey @kosinusbch ! The guideline specifies that identifiers must be higher than 0x00 00 00 0F and lower than 0x10 00 00 00. So the first character should be `0`.  If you wish I can adjust your identifier to `0x08080C00` instead. You can also update your PR. Let me know what would work best for you.

**Comment by kosinusbch** [comment]
@jcramer Yeah, I'd be interested in that. The most time-consuming part of BCH-DNS right now would be to get everything ready for the OpenNIC application, so taking some load off the more technical work would be great

**Comment by jcramer** [comment]
Cool. Would you mind sending me an email at jcramer@deskviz.com so I can have your email?

**Pull request merged**
